package com.example.lenovo.project;

import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.text.TextUtils;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.GridView;
import android.widget.Toast;

import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.AdView;
import com.google.android.gms.ads.MobileAds;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;

public class ContactFragment extends Fragment {
    EditText Email;
    EditText Suggestion;
    Button add;

    String email;
    String suggestion;
    private FirebaseAuth firebaseAuth;

    private static final String APP_ID="ca-app-pub-3940256099942544~3347511713";
    AdView mAdview;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view=inflater.inflate(R.layout.fragment_contact,container,false);
        add=(Button)view.findViewById(R.id.suggestion);
        Email=(EditText)view.findViewById(R.id.emailsuggestion);
        Suggestion=(EditText)view.findViewById(R.id.textsuggestion);
        firebaseAuth=FirebaseAuth.getInstance();
        MobileAds.initialize(getActivity(),APP_ID);
        mAdview=(AdView) view.findViewById(R.id.adView);
        AdRequest adRequest=new AdRequest.Builder().build();
        mAdview.loadAd(adRequest);



        add.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(notEmpty())
                {
                    DatabaseReference userTableRef= FirebaseDatabase.getInstance().getReference("suggestions");
                    Suggestion latest=new Suggestion();
                    latest.setSuggestion(suggestion);
                    latest.setUseremail(email);
                    String autogeneratedKey=userTableRef.push().getKey();
                    userTableRef.child(autogeneratedKey).setValue(latest);
                    succesful();
                }
            }


        });
        return view;
    }
    private void succesful() {
        Email.setText("");
        Suggestion.setText("");
        Toast.makeText(getContext(),"Thank you for your Suggestions",Toast.LENGTH_SHORT).show();
    }
    public boolean notEmpty()
    {
        email=Email.getText().toString();
        suggestion=Suggestion.getText().toString();
        if(TextUtils.isEmpty(email))
        {
            Toast.makeText(getContext(),"Please Enter Email",Toast.LENGTH_SHORT).show();
            return false;
        }
        if(TextUtils.isEmpty(suggestion))
        {
            Toast.makeText(getContext(),"Please Enter Message",Toast.LENGTH_SHORT).show();
            return false ;
        }
        return true;
    }

}
